### ISSUE TITLE
whenever/capistrano `method_missing_with_variables': undefined method `role_names_for_host'

### ISSUE THREAD

**Issue by martinffx** [javan/whenever#302]
When I update my version of whenever to 0.8.1 or 0.8.2 from 0.8.0 I get the following error:

https://gist.github.com/1784b9644c7c679cf7e0

It looks like it is failing to set the roles even though I set them like so:

```
set_default(:whenever_roles, [:workers])
```

I've included my whenever_crontab.rb in the gist
